// webviewer-nuxtjs/components/WebViewer.vue
<template>
  <div id="webviewer" ref="viewer" />
</template>

<script>
export default {
  name: 'WebViewer',
  props: {
    url: String
  },
  mounted () {
    import('@pdftron/webviewer').then(() => {
      WebViewer.Iframe({
        path: '/lib/webviewer',
        initialDoc: this.url, // replace with your own PDF file
        licenseKey: 'your_license_key' // sign up to get a free trial key at https://dev.apryse.com
      }, this.$refs.viewer).then((instance) => {
        // call apis here
      });
    });
  }
};
</script>

<style>
#webviewer {
  height: 100vh;
}
</style>

// webviewer-svelte/src/WebViewer.svelte
<script>

  import { onMount, createEventDispatcher } from 'svelte';
  import WebViewer from '@pdftron/webviewer';

  let instance = null;
  const dispatch = createEventDispatcher();

	onMount(async () => {
		const ele = document.getElementById('viewer');
		WebViewer({
      path: '/lib/webviewer',
			licenseKey: 'YOUR_LICENSE_KEY',
			initialDoc: 'https://apryse.s3.amazonaws.com/public/files/samples/WebviewerDemoDoc.pdf',
		}, ele).then(instance => {
			dispatch('ready', {
				instance
			})
		})
	});

</script>

<style>
	#viewer {
		width: 100%;
		height: 100vh;
	}
</style>

<div id='viewer'>

</div>
